CREATE TABLE test (
    test_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    qty INT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE test ADD COLUMN price FLOAT FIRST;
ALTER TABLE test DROP COLUMN price;

ALTER TABLE test MODIFY COLUMN price decimal(10,3) NOT NULL;

ALTER TABLE test RENAME COLUMN price to  prices;
ALTER TABLE test RENAME to test;

ALTER TABLE tests MODIFY COLUMN prices decimal(10,3) NOT NULL DEFAULT 10;
ALTER TABLE tests MODIFY COLUMN prices decimal(10,3)  DEFAULT NULL;